name: 📦 Publish to npm

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create .npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.FLEEKXYZ_NPM_TOKEN }}" > .npmrc
          echo "@fleek-platform:registry=https://registry.npmjs.org" >> .npmrc
          cat .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
